<?php
$ci = get_instance();
$ci->load->model('CommonModel');
$sql = $ci->CommonModel->GetProducts();
// $query = $ci->db->query($sql);
echo "<pre>";
print_r($query);

$product_name = ["Nexus - UK Edition", "Outside Magazine - US Edition", "Oxygen Magazine - US Edition", "Outdoor Photography Magazine - US Edition", "Outlook Business Magazine", "Outside Magazine - US Edition", "Oxygen Magazine - US Edition", "Popular Mechanics Magazine US Edition", "Popular Photography and Imaging Magazine - US Edition", "Psychology Today Magazine US Edition"];
//////////////////////////////
$product_title = ["Nexus - UK Edition Magazine | Get 10% Off on Magazine Subscription", "Outside Magazine - US Subscription | Outdoor Magazine Online", "Oxygen Magazine - US Edition Subscription | Get 11% Off", "Outdoor Photography Magazine - US Subscription | Art & Photography", "Outlook Business Magazine Subscription | Business Magazine Online", "Outside Magazine - US Subscription | Outdoor Magazine Online", "Oxygen Magazine - US Edition Subscription | Get 11% Off", "Popular Mechanics Magazine US Subscription | Science & Technology", "Popular Photography and Imaging Magazine - US Edition Subscription", "Buy Psychology Today Magazine US Edition | Psychology Literature"];
/////////////////////////////////////////
$product_keyword = ["Nexus - UK Edition, Buy Nexus - UK Edition, Subscribe Nexus - UK Edition, Indiamags, Nexus UK, Nexus UK Magazine, Buy Nexus Magazine UK, Subscribe Nexus Magazine UK, Medical, Future Science", "Outside Magazine - US Edition, Buy Outside Magazine - US Edition, Subscribe Outside Magazine - US Edition, Online Magazine Subscription, Indiamags, Outdoor Magazine, Travel, Sport, Health, Fitness, Environment, Personalities", "Oxygen Magazine - US Edition, Buy Oxygen Magazine - US Edition, Subscribe Oxygen Magazine - US Edition, Online Magazine Subscription, Indiamags, Fitness Magazine, Women\'s Magazine", "Outdoor Photography Magazine - US Edition, Buy Outdoor Photography Magazine - US Edition, Subscribe Outdoor Photography Magazine - US Edition, Online Magazine Subscription, Indiamags, Outdoor, Photographer, Photo, Camera, Nature, Landscape, Photos", "Outlook Business Magazine, Buy Outlook Business Magazine, Subscribe Outlook Business Magazine, Outlook Magazine, Online Magazine Subscription, Indiamags, Business Magazine, Business India", "Outside Magazine - US Edition, Buy Outside Magazine - US Edition, Subscribe Outside Magazine - US Edition, Online Magazine Subscription, Indiamags, Outdoor Magazine, Travel, Sport, Health, Fitness, Environment, Personalities", "Oxygen Magazine - US Edition, Buy Oxygen Magazine - US Edition, Subscribe Oxygen Magazine - US Edition, Online Magazine Subscription, Indiamags, Fitness Magazine, Women\'s Magazine", "Popular Mechanics Magazine US Edition, Buy Popular Mechanics Magazine US Edition, Subscribe Popular Mechanics Magazine US Edition, Online Magazine Subscription, Indiamags, Mechanics, Science, Technology, Gadgets, Electronics, Automotive, DIY, Tools, Mechanics, Home Improvement, Military, Computers, Home Science", "Popular Photography and Imaging Magazine - US Edition, Buy Popular Photography and Imaging Magazine - US Edition, Subscribe Popular Photography and Imaging Magazine - US Edition, Photography Magazine, Online Magazine Subscription, Indiamags", "Psychology Today Magazine US Edition, Buy Psychology Today Magazine US Edition, Subscribe Psychology Today Magazine US Edition, Online Magazine Subscription, Indiamags, Psychology, Neuroscience, Health, Science Journalist"];
/////////////////////////////
$product_description = ["Subscribe Nexus - UK Edition magazine on Indiamags at best price. Nexus - UK Edition magazine covers health issues including alternative medicine and future science.", "Subscribe Outside Magazine - US Edition on Indiamags which is a magazine which is dedicated to covering the people, activities, politics, art, and literature of the outdoors.", "Subscribe Oxygen Magazine - US Edition on Indiamags which is designed to inform, educate and inspire women of all ages about benefits of fitness, proper nutrition, health.", "Subscribe Outdoor Photography Magazine - US Edition which is magazine passionate about being out in wild places, seeing inspiring nature and having great adventures.", "Subscribe Outlook Business Magazine which updates you on all the business related magazine. They provide all about leadership, grounded views, rare insights and fresh perspectives.", "Subscribe Outside Magazine - US Edition on Indiamags which is a magazine which is dedicated to covering the people, activities, politics, art, and literature of the outdoors.", "Subscribe Oxygen Magazine - US Edition on Indiamags which is designed to inform, educate and inspire women of all ages about benefits of fitness, proper nutrition, health.", "Subscribe Popular Mechanics Magazine US Edition which is science and technolgy magazine covering automotive, electronics, science, technology, space, gadgets and more.", "Subscribe Popular Photography and Imaging Magazine - US Edition on Indiamags which is the worldâ€™s largest photography magazine giving all the information on the camera.", "Subscribe Psychology Today Magazine US Edition where its intent is to make psychology literature more accessible to the general public, focusing on behavior, neuroscience etc."];
///////////////////////////////////////////
// foreach ($product_name as $key => $value) {
//     echo "UPDATE `products` SET `meta_keyword`= '$product_keyword[$key]', `meta_description`= '$product_description[$key]' ,`meta_title` = '$product_title[$key]' WHERE `name` = '$value' ;" . "</br>";
// }
